// Local English UI strings. Backend language remains Russian or Kyrgyz.
export const en: Record<string, string> = {
  'Месяц': 'Month',
  'Картой': 'Card',
  'Наличными': 'Cash',
  'Бонусы': 'Bonuses',
  'Отзывы': 'Reviews',
  'Отзывы о ресторане': 'Restaurant reviews',
  'Закрыть отзывы ресторана': 'Close restaurant reviews',
  'оценок': 'ratings',
  'отзывов': 'reviews',
  'Сортировка отзывов': 'Sort reviews',
  'По умолчанию': 'Default',
  'Сначала новые': 'Newest first',
  'Сначала хорошие': 'Good reviews first',
  'Сначала плохие': 'Bad reviews first',
  'Закрыть сортировку отзывов': 'Close review sorting',
  'Сейчас закрыто': 'Currently closed',
  'Ресторан сейчас закрыт': 'The restaurant is currently closed',
  'До бесплатной доставки осталось': 'Remaining until free delivery',
  'Бесплатно от': 'Free delivery from',
  'С высокой оценкой': 'Highest rating',
  'С низкой оценкой': 'Lowest rating',
  'Загружаем отзывы…': 'Loading reviews…',
  'Не удалось загрузить отзывы': 'Could not load reviews',
  'Отзывов пока нет': 'No reviews yet',
  'Здесь появятся отзывы клиентов о ресторане.': 'Customer reviews of this restaurant will appear here.',
  'из 5': 'out of 5',
  'Текущие условия': 'Current conditions',
  'Цена доставки зависит от размера корзины, расстояния до ресторана и других факторов. Соберите заказ и мы рассчитаем финальную стоимость': 'The delivery price depends on your basket, distance to the restaurant and other factors. Add your items and we will calculate the final price.',
  "Поиск ресторанов": "Search restaurants",
  "Фильтры": "Filters",
  "Кухня": "Cuisine",
  "Сбросить фильтр": "Clear filter",
  "Закрыть фильтры": "Close filters",
  "Показать рестораны": "Show restaurants",
  "Доброе утро!": "Good morning!",
  "Куда отправимся сегодня?": "Where are we going today?",
  "Быстро и комфортно": "Fast and comfortable",
  "Грузовой": "Freight",
  "Доставка больших грузов": "Delivery of large loads",
  "Доставка еды": "Food delivery",
  "Из ресторанов": "From restaurants",
  "Любимые рестораны рядом": "Favorite restaurants nearby",
  "Куда поедем?": "Where will we go?",
  "Еда": "Food",
  "Закрыть уведомления": "Close notifications",
  "Повторить загрузку уведомлений": "Retry downloading notifications",
  "Пока нет уведомлений": "No notifications yet",
  "Изменить свой адрес": "Change your address",
  "Укажите свой адрес": "Enter your address",
  "Быстрые заказы рядом": "Fast orders nearby",
  "Быстрые\nзаказы рядом!": "Fast\norders are nearby!",
  "Всё, что нужно —\nуже рядом": "All you need is\nalready close",
  "Выбрать адрес": "Select address",
  "Дом": "Home",
  "Работа": "Work",
  "Адрес дома": "Home address",
  "Адрес работы": "Work address",
  "Избранный адрес": "Favorite address",
  "Введите адрес": "Enter address",
  "Выберите адрес": "Select address",
  "Введите улицу или выберите точку на карте.": "Enter a street or select a point on the map.",
  "Начните вводить улицу или название места.": "Start typing a street or place name.",
  "Не удалось сохранить адрес": "Failed to save address",
  "Удерживайте, чтобы изменить адрес": "Hold to change address",
  "Избранное": "Favorites",
  "добавить адрес": "add address",
  "Добавить": "Add",
  "Открыть активный заказ еды": "Open active food order",
  "Заказ уже в работе": "The order is already in progress",
  "Посмотреть статус доставки": "View delivery status",
  "Вкуснее\nкаждый день": "Tastier\nevery day",
  "Скидки до 30%\nна доставку еды": "Discounts up to 30%\nfor food delivery",
  "Заказать еду": "Order food",
  "Скоро появится": "Coming soon",
  "Баннер": "Banner",
  "из": "from",
  "Строим маршрут": "Building a route",
  "Вы отклонились от маршрута": "You have deviated from the route",
  "Маршрут недоступен": "Route unavailable",
  "Готовим навигацию": "Preparing the navigation",
  "Проверить местоположение": "Check location",
  "Повторить": "Repeat",
  "Проверить": "Check",
  "Стоп": "Stop",
  "Уступи дорогу": "Give way",
  "Ограничение 60": "Limit 60",
  "Пешеходный переход": "Pedestrian crossing",
  "Камера скорости": "Speed camera",
  "Светофор": "Traffic light",
  "уже позади": "already behind",
  "рядом": "nearby",
  "Очистить поиск": "Clear search",
  "Открыть корзину": "Open cart",
  "товаров": "goods",
  "Корзина": "Cart",
  "Ваш заказ": "Your order",
  "Рестораны": "Restaurants",
  "Ресторан, кухня или блюдо": "Restaurant, cuisine or dish",
  "Суши": "Sushi",
  "Пицца": "Pizza",
  "Фастфуд": "Fast food",
  "Национальная кухня": "Local cuisine",
  "Ищем рестораны…": "Finding restaurants…",
  "Не удалось загрузить рестораны": "Failed to load restaurants",
  "мин": "min",
  "Бесплатная доставка": "Free delivery",
  "Доставка": "Delivery",
  "Рестораны скоро появятся": "Restaurants coming soon",
  "Ничего не найдено": "Nothing found",
  "Мы готовим каталог. Загляните немного позже.": "We are preparing a catalogue. Check back a little later.",
  "Попробуйте другую кухню или измените запрос.": "Try a different cuisine or change your request.",
  "Поиск по меню": "Search by menu",
  "Информация о ресторане": "Restaurant information",
  "Бесплатная доставка от": "Free delivery from",
  "Адрес": "Address",
  "Блюда не найдены": "No dishes found",
  "Измените запрос.": "Change your request.",
  "Выберите другую категорию.": "Select another category.",
  "Закрыть информацию о ресторане": "Close restaurant information",
  "бесплатно": "free",
  "Минимальный заказ": "Minimum order",
  "Без минимальной суммы заказа": "No minimum order amount",
  "Демонстрационный ресторан. Заказы не передаются в реальное заведение.": "Demonstration restaurant. Orders are not transferred to the actual establishment.",
  "Выберите количество": "Select quantity",
  "Комплектация и добавки": "Options and extras",
  "По желанию": "Optional",
  "Бесплатно": "Free",
  "Добавить в корзину": "Add to cart",
  "Блюдо временно недоступно": "Dish temporarily unavailable",
  "Пока ничего не сохранено": "Nothing saved yet",
  "Нажмите на сердечко у ресторана или блюда, чтобы найти его здесь.": "Tap the heart on a restaurant or dish to save it here.",
  "Блюда": "Dishes",
  "ресторан": "restaurant",
  "блюдо": "dish",
  "Убрать из избранного": "Remove from favorites",
  "Добавить в избранное": "Add to favorites",
  "Дождитесь завершения оформления заказа": "Wait until your order is completed",
  "Назад недоступно: заказ оформляется": "Back not available: order is being processed",
  "Очистить корзину": "Clear cart",
  "Заказ из ресторана": "Order from a restaurant",
  "за шт.": "per piece",
  "Нет в наличии": "Out of stock",
  "порция": "portion",
  "порций": "servings",
  "по одной к каждой порции блюда": "one for each portion of the dish",
  "Оставить": "Leave",
  "Убрать": "Remove",
  "шт.": "pcs.",
  "Состав меню изменился. Уберите недоступные блюда.": "The menu composition has changed. Remove unavailable items.",
  "Оформить заказ": "Place an order",
  "Меню изменилось": "The menu has changed",
  "В корзине пока пусто": "The cart is still empty",
  "Сохранённые блюда больше недоступны. Очистите корзину и выберите другие.": "Saved dishes are no longer available. Empty the trash and select others.",
  "Добавьте любимые блюда из меню ресторана.": "Add your favorite dishes from the restaurant menu.",
  "Выбрать блюда": "Select dishes",
  "Оформление заказа": "Placing an order",
  "Адрес доставки": "Delivery address",
  "Укажите адрес": "Please enter your address",
  "Изменить адрес доставки": "Change delivery address",
  "Изменить": "Edit",
  "Комментарий к заказу": "Comments on the order",
  "Например: домофон, подъезд, этаж": "For example: intercom, entrance, floor",
  "Наличными курьеру": "Cash to courier",
  "Оплата картой": "Payment by card",
  "Онлайн оплата": "Online payment",
  "Пока недоступно": "Not yet available",
  "Включая доставку": "Including delivery",
  "Закрыть адрес": "Close address",
  "Улица и номер дома": "Street and house number",
  "Сохранить адрес": "Save address",
  "Заказ": "Order",
  "Ожидаем подтверждения": "We are waiting for confirmation",
  "Заказ подтверждён": "Order confirmed",
  "Ваш заказ готовится": "Your order is being prepared",
  "Можно забирать": "Can be picked up",
  "Заказ готов": "The order is ready",
  "Курьер уже в пути": "The courier is on his way",
  "Заказ получен": "Order received",
  "Заказ доставлен": "Order delivered",
  "Принят": "Accepted",
  "Готовится": "Getting ready",
  "Доставлен": "Delivered",
  "Ресторан принимает ваш заказ": "The restaurant accepts your order",
  "Передаём заказ курьеру": "We transfer the order to the courier",
  "Курьер скоро будет у вас": "The courier will be with you soon",
  "Спасибо за заказ!": "Thanks for your order!",
  "Ресторан отменил заказ": "The restaurant canceled the order",
  "Ресторан уже готовит блюда": "The restaurant is already preparing dishes",
  "поз.": "pos.",
  "АДРЕС ДОСТАВКИ": "DELIVERY ADDRESS",
  "Адрес не указан": "Address not specified",
  "Связаться с рестораном": "Contact the restaurant",
  "Контакт ресторана": "Restaurant contact",
  "Ресторан пока не указал номер телефона.": "The restaurant has not yet provided a phone number.",
  "Нажмите, чтобы обновить статус": "Click to update status",
  "Тестовый заказ · ресторан из макетов": "Test order · restaurant from mock-ups",
  "Заказов пока нет": "No orders yet",
  "Здесь появятся ваши заказы из ресторанов.": "Your orders from restaurants will appear here.",
  "Доставка временно недоступна. Попробуйте обновить раздел немного позже.": "Delivery is temporarily unavailable. Try updating the section a little later.",
  "Количество порций": "Number of servings",
  "Можно добавить не больше": "No more can be added",
  "порций одного блюда с одинаковыми добавками.": "servings of one dish with the same additives.",
  "Заказ из другого ресторана": "Order from another restaurant",
  "В одном заказе могут быть блюда только из одного ресторана. Заменить содержимое корзины?": "One order can only contain dishes from one restaurant. Replace the contents of the cart?",
  "Заменить": "Replace",
  "Очистить корзину?": "Clear cart?",
  "Все блюда и добавки будут удалены из корзины.": "All meals and add-ons will be removed from your cart.",
  "Очистить": "Clear",
  "Без этой добавки получится больше": "Without this additive you will get more",
  "одинаковых порций. Сначала уменьшите количество блюда.": "identical portions. First reduce the quantity of the dish.",
  "Открыть допуски и документы": "Open permits and documents",
  "Главная": "Home",
  "Заказать такси": "Order a taxi",
  "Доставка и грузовой": "Delivery and freight",
  "Мои заказы еды": "My food orders",
  "Допуски и документы": "Approvals and documents",
  "Закрыть поиск": "Close search",
  "в пути": "on the way",
  "Расчёт стоимости": "Cost calculation",
  "Оплата водителю после поездки": "Payment to the driver after the trip",
  "Данные водителя загружаются": "Driver data is loading",
  "Строим маршрут до клиента…": "We are building a route to the client...",
  "Ожидаем GPS водителя": "We are waiting for the GPS driver",
  "Отправитель": "Sender",
  "От двери до двери": "Door to door",
  "К новым заказам": "For new orders",
  "Пассажир увидит, что заказ отменён.": "The passenger will see that the order has been cancelled.",
  "прибытие ≈": "arrival ≈",
  "Включить навигацию и положение в фоне": "Enable navigation and background position",
  "до клиента": "to the client",
  "до цели": "to the goal",
  "по прямой": "in a straight line",
  "мин бесплатно после начала": "min free after start",
  "Затем": "Then",
  "Указать адреса": "Specify addresses",
  "Заказать доставку": "Order delivery",
  "Свернуть параметры": "Collapse options",
  "Параметры доставки": "Delivery options",
  "Адрес отправки": "Pickup address",
  "Определяем местоположение": "Determining the location",
  "Куда доставить": "Where to deliver",
  "Закрыть параметры доставки": "Close delivery options",
  "Стоимость после маршрута": "Cost after route",
  "Запланировать поездку": "Plan a trip",
  "Подача через 30 минут": "Serve in 30 minutes",
  "Водитель заберёт и передаст груз у двери": "The driver will pick up and hand over the cargo at the door",
  "Укажите важные детали": "Provide important details",
  "Закрыть способы оплаты": "Close payment methods",
  "Расчёт цены": "Price calculation",
  "Груз": "Cargo",
  "от двери до двери": "door to door",
  "Суши · Роллы": "Sushi · Rolls",
  "Бургеры": "Burgers",
  "Курица": "Chicken",
  "Закуски": "Snacks",
  "Роллы": "Rolls",
  "1 шт.": "1 piece",
  "Куда едем?": "Where are we going?",
  "Такси": "Taxi",
  "Место подачи": "Place of delivery",
  "Укажите место подачи": "Specify delivery location",
  "Укажите адрес или включите GPS": "Enter your address or turn on GPS",
  "Ваш адрес": "Your address",
  "Выберите место подачи": "Select delivery location",
  "Считаем стоимость…": "We calculate the cost...",
  "Считаем…": "We think...",
  "Повторим автоматически": "Repeat automatically",
  "Обновляем цену…": "We update the price...",
  "Загружаем тарифы…": "Loading tariffs...",
  "Выберите тариф": "Select tariff",
  "Подъезд": "Entrance",
  "Укажите номер подъезда": "Enter the entrance number",
  "Пожелания к поездке": "Travel wishes",
  "С питомцем": "With a pet",
  "Перевозку питомца согласуйте с водителем.": "Coordinate transportation of your pet with the driver.",
  "Заказ другому человеку": "Order to another person",
  "Имя и телефон пассажира для водителя": "Passenger's name and telephone number for the driver",
  "Водитель увидит имя и телефон этого пассажира": "The driver will see the name and phone number of this passenger",
  "Имя пассажира": "Passenger name",
  "Телефон пассажира": "Passenger phone",
  "Выбрать из контактов": "Select from contacts",
  "Убрать пассажира": "Remove passenger",
  "Укажите имя и номер телефона пассажира": "Please provide the passenger's name and telephone number",
  "Контакты на этом устройстве недоступны": "Contacts are not available on this device",
  "Разрешите доступ к контактам в настройках телефона": "Allow access to contacts in your phone settings",
  "У выбранного контакта нет номера телефона": "The selected contact does not have a phone number",
  "Не удалось открыть контакты": "Failed to open contacts",
  "Чат с заказчиком": "Chat with the customer",
  "Например, 2": "For example, 2",
  "Напишите здесь": "Write here",
  "Изменить место подачи": "Change delivery location",
  "Изменить пункт назначения": "Change destination",
  "Точка посадки": "Landing point",
  "Пункт назначения": "Destination",
  "Откуда поедем?": "Where will we go from?",
  "Карта": "Map",
  "Ваше местоположение": "Your location",
  "Определим по GPS": "Determined by GPS",
  "Разрешите доступ к геолокации": "Allow access to geolocation",
  "Так мы быстрее найдём место подачи и покажем вашу точку на карте. Геолокация используется только во время работы приложения.": "This way we will quickly find the delivery location and show your point on the map. Geolocation is used only while the application is running.",
  "Так вы сможете быстро увидеть своё положение на карте. Геолокация используется только во время работы приложения.": "This way you can quickly see your position on the map. Geolocation is used only while the application is running.",
  "Не пропустите важное": "Don't miss important things",
  "Сообщим, когда водитель назначен, приехал, написал вам и завершил поездку.": "We'll let you know when the driver is assigned, arrives, texts you, and completes the trip.",
  "Сообщим о новом заказе, сообщении пассажира, когда пассажир выходит, и о завершении поездки.": "We'll notify you about new orders, passenger messages, pickup readiness, and completed trips.",
  "Разрешить доступ": "Allow access",
  "Включить уведомления": "Enable notifications",
  "Указать адрес вручную": "Specify the address manually",
  "Не сейчас": "Not now",
  "Открыть настройки": "Open settings",
  "Разрешение телефона выключено": "Phone permission is turned off",
  "Разрешите уведомления, чтобы не пропустить события поездки.": "Allow notifications so you don't miss any travel events.",
  "Разрешите уведомления в настройках устройства.": "Allow notifications in your device settings.",
  "Разрешите доступ к местоположению в настройках устройства.": "Allow location access in your device settings.",
  "Разрешите доступ к местоположению или выберите адрес вручную.": "Allow access to the location or select the address manually.",
  "Включите геолокацию в настройках устройства.": "Enable geolocation in your device settings.",
  "Не удалось определить местоположение. Попробуйте ещё раз или выберите адрес вручную.": "The location could not be determined. Try again or select the address manually.",
  "Шаг 1 из 2": "Step 1 of 2",
  "Шаг 2 из 2": "Step 2 of 2",
  "Ищем адреса…": "We are looking for addresses...",
  "Повторить поиск": "Repeat search",
  "Куда отправимся?": "Where will we go?",
  "Введите улицу, номер дома или название места.": "Enter a street, house number or place name.",
  "Стоимость устарела. Обновите расчёт.": "The cost is outdated. Update the calculation.",
  "Поменять адреса местами": "Swap addresses",
  "Очистить адрес": "Clear address",
  "Сервер вернул некорректный ответ. Попробуйте ещё раз.": "The server returned an incorrect response. Try again.",
  "Сервер долго не отвечает. Повторите попытку через несколько секунд.": "The server does not respond for a long time. Please try again in a few seconds.",
  "Не удалось подключиться к серверу. Проверьте интернет и повторите попытку.": "Failed to connect to the server. Check your internet and try again.",
  "Меню": "Menu",
  "Оценка": "Evaluation",
  "Повторить подключение": "Reconnect",
  "Выйти из аккаунта": "Log out of your account",
  "Расчёт устарел. Рассчитайте стоимость ещё раз.": "The calculation is outdated. Calculate the cost again.",
  "Нет связи. Проверьте интернет · Повторить": "No connection. Check the Internet · Repeat",
  "Восстанавливаем соединение…": "Reestablishing connection...",
  "Диспетчер проверит профиль и автомобиль. После подтверждения здесь появятся заказы.": "The dispatcher will check the profile and the car. Once confirmed, orders will appear here.",
  "Предложения появятся, когда рядом будет пассажир.": "Offers will appear when a passenger is nearby.",
  "Включите режим на линии, чтобы получать доступные заказы.": "Turn on online mode to receive available orders.",
  "Комфортные поездки": "Comfortable trips",
  "за поездку": "per trip",
  "минимум": "minimum",
  "от": "from",
  "каждый день": "every day",
  "Тарифы пока недоступны": "Tariffs are not yet available",
  "Development: тестовый маршрут. Проверьте боевой ключ маршрутизации перед реальными поездками.": "Development: test route. Check the combat routing key before real trips.",
  "Номер клиента": "Client number",
  "Номер водителя": "Driver number",
  "SMS подтверждает ваш номер. Данные поездки доступны только вам и назначенному водителю.": "SMS confirms your number. Trip data is available only to you and the designated driver.",
  "Политика конфиденциальности": "Privacy Policy",
  "Следуйте к пассажиру": "Follow the passenger",
  "Ожидайте пассажира": "Wait for a passenger",
  "Взять заказ": "Take order",
  "Свернуть детали поездки": "Collapse trip details",
  "Раскрыть детали поездки": "Reveal trip details",
  "Проведите вправо": "Swipe right",
  "Сейчас нет свободных водителей. Попробуйте ещё раз.": "There are currently no available drivers. Try again.",
  "Вы можете оформить новую поездку.": "You can arrange a new trip.",
  "Предлагаем заказ свободным водителям": "Offering the order to available drivers",
  "завершённых поездок за период": "completed trips for the period",
  "Пополнение через администратора. Комиссия списывается после завершения поездки.": "Replenishment through the administrator. The commission is debited after the trip is completed.",
  "Наличные вы получаете от пассажиров. Они не зачисляются на депозит.": "You receive cash from passengers. They are not credited to the deposit.",
  "Комиссия за поездку": "Trip commission",
  "Пополнение депозита": "Deposit replenishment",
  "Остаток": "Remainder",
  "Остаток:": "Remaining:",
  "Все поездки оплачиваются наличными в сомах после завершения. Стоимость фиксируется перед заказом.": "All trips are paid in cash in soms upon completion. The cost is fixed before ordering.",
  "Если возникла проблема с поездкой, сообщите время заказа и номер телефона аккаунта.": "If there is a problem with your trip, please provide your order time and account phone number.",
  "Контакт поддержки пока не настроен. Обратитесь к диспетчеру сервиса.": "The support contact has not yet been set up. Contact the service manager.",
  "Карты — OpenStreetMap, маршруты — OSRM.": "Maps - OpenStreetMap, routes - OSRM.",
  "© Участники OpenStreetMap ↗": "© OpenStreetMap Contributors ↗",
  "Политика конфиденциальности ↗": "Privacy Policy ↗",
  "Development: адреса из тестового каталога сервера. Для поиска любых адресов требуется ключ Яндекс.": "Development: addresses from the server's test directory. To search for any addresses, a Yandex key is required.",
  "Адрес не найден": "Address not found",
  "Уточните название улицы или выберите точку на карте.": "Check the street name or select a point on the map.",
  "Отправить сообщение": "Send message",
  "Развернуть или свернуть панель": "Expand or collapse a panel",
  "Нет связи с сервером. Проверьте интернет и повторите попытку.": "No connection to the server. Check your internet and try again.",
  "Не удалось выполнить действие. Попробуйте ещё раз.": "The action failed. Try again.",
  "Войдите в аккаунт заново.": "Sign in to your account again.",
  "Сессия завершена.": "The session has ended.",
  "Фотография профиля": "Profile photo",
  "Выбрать фото": "Select photo",
  "Изменить фото": "Change photo",
  "Выберите квадратную область фотографии.": "Select a square area of the photo.",
  "Выберите изображение JPG, PNG или WEBP.": "Select a JPG, PNG or WEBP image.",
  "Файл фотографии должен быть не больше 5 МБ.": "The photo file must be no more than 5 MB.",
  "Вход в приложение": "Sign in to Atlas",
  "Быстрые и безопасные поездки\nвсегда рядом": "Fast and safe rides\nalways nearby",
  "Номер телефона": "Phone number",
  "Код из SMS": "Code from SMS",
  "Отправить код": "Send code",
  "Отправить ещё раз": "Send again",
  "Продолжить": "Continue",
  "Откуда": "Where from",
  "Куда": "Where",
  "Моё местоположение": "My location",
  "Найти адрес": "Find an address",
  "Выбрать на карте": "Select on map",
  "Выберите точку на карте": "Select a point on the map",
  "Тариф": "Tariff",
  "Наличные": "Cash",
  "Оплата водителю": "Payment to the driver",
  "Заказать": "Order",
  "Комментарий водителю": "Comment to the driver",
  "Рассчитать стоимость": "Calculate cost",
  "Выберите маршрут": "Choose a route",
  "Ищем водителя": "We are looking for a driver",
  "Водитель выехал к вам": "The driver has come to you",
  "Водитель приехал": "The driver has arrived",
  "Поездка началась": "The trip has begun",
  "Заказ успешно выполнен": "Order completed successfully",
  "Водитель не найден": "Driver not found",
  "Заказ отменён": "Order canceled",
  "Отменить заказ": "Cancel order",
  "Я выхожу": "I'm going out",
  "Позвонить": "Call",
  "Чат": "Chat",
  "Готово": "Done",
  "Оцените поездку": "Rate the trip",
  "Спасибо, что выбрали Atlas": "Thank you for choosing Atlas",
  "Заказать снова": "Order again",
  "На линии": "On line",
  "Не на линии": "Not on line",
  "Новый заказ": "New order",
  "Принять": "Accept",
  "Пропустить": "Skip",
  "Приехал": "Arrived",
  "Начать поездку": "Start your trip",
  "Завершить поездку": "End the trip",
  "Профиль": "Profile",
  "История поездок": "Travel history",
  "История заказов": "Order history",
  "История": "History",
  "Настройки": "Settings",
  "Поддержка": "Support",
  "Способы оплаты": "Payment methods",
  "Выйти": "Log out",
  "Баланс": "Balance",
  "Сегодня": "Today",
  "Неделя": "Week",
  "Все": "All",
  "Сохранить": "Save",
  "Имя": "Name",
  "Фотография — ссылка HTTPS": "Photo - HTTPS link",
  "Уведомления": "Notifications",
  "Язык интерфейса": "Interface language",
  "Русский": "Russian",
  "Кыргызский": "Kyrgyz",
  "Новых заказов пока нет": "No new orders yet",
  "Вы не на линии": "You're offline",
  "Выйти на линию": "Go online",
  "Ожидаем подтверждение": "We are waiting for confirmation",
  "Депозит для комиссии": "Deposit for commission",
  "Доход наличными": "Cash income",
  "Комиссия сервиса": "Service commission",
  "История операций": "Operation history",
  "Поездок пока нет": "No trips yet",
  "Операций пока нет": "No operations yet",
  "Обновить": "Update",
  "Завершён": "Completed",
  "Отменён": "Canceled",
  "В пути": "On the way",
  "Поиск": "Search",
  "Ожидание": "Waiting",
  "Найден": "Found",
  "Нет водителя": "No driver",
  "До клиента": "To pickup",
  "Расстояние": "Distance",
  "Стоимость": "Cost",
  "Ваше сообщение": "Your message",
  "Напишите первое сообщение": "Write your first message",
  "Пассажир": "Passenger",
  "Водитель": "Driver",
  "Закрыть": "Close",
  "Назад": "Back",
  "Детали поездки": "Trip details",
  "Подтверждён": "Confirmed",
  "Подключаемся…": "Connecting…",
  "Маршрут поездки": "Travel route",
  "Уже отправлено": "Already sent",
  "Пассажир выходит": "Passenger is coming out",
  "Новый расчёт": "New calculation",
  "Платёж": "Payment",
  "Автомобиль": "Car",
  "Рейтинг": "Rating",
  "Пока нет оценок": "No ratings yet",
  "Близкая подача": "Nearby pickup",
  "Средняя подача": "Moderate pickup distance",
  "Дальняя подача": "Long pickup distance",
  "Подача рассчитывается": "Calculating pickup time",
  "До клиента · расстояние и время по дороге": "To the client · distance and time on the road",
  "Время поездки": "Travel time",
  "Оцените пассажира": "Rate the passenger",
  "Оценить клиента": "Rate the client",
  "Ваш водитель": "Your driver",
  "Информация о поездке": "Travel information",
  "Дата": "Date",
  "Время заказа": "Order time",
  "Время завершения": "End time",
  "Расчётное время в пути": "Estimated travel time",
  "Статус": "Status",
  "Оплата": "Payment",
  "Стоимость поездки": "Trip cost",
  "Предварительная стоимость": "Preliminary cost",
  "Способ оплаты": "Payment method",
  "Итого": "Total",
  "Оплата не проводилась": "Payment was not made",
  "Ваша оценка": "Your rating",
  "Комментарий": "Comment",
  "Поездка не найдена": "Trip not found",
  "Не удалось позвонить": "Could not place the call",
  "Уточним время": "Time to be confirmed",
  "Подробные условия доставки": "Delivery details",
  "Уточним доставку": "Delivery to be confirmed",
  "До бесплатной": "Until free delivery",
  "Закрыть корзину": "Close cart",
  "Меню обновляется": "Updating menu",
  "Блюдо больше недоступно": "Dish is no longer available",
  "Удалить": "Remove",
  "Добавить к заказу": "Add to order",
  "Товары": "Items",
  "К оформлению": "Go to checkout",
  "Улица, дом, квартира, город": "Street, building, apartment, city",
  "Уточняется": "Being confirmed",
  "Закрыть информацию о доставке": "Close delivery information",
  "Доставка бесплатно": "Free delivery",
  "Информация о доставке": "Delivery information",
  "До бесплатной доставки": "Until free delivery",
  "Укажите адрес при оформлении": "Enter an address at checkout",
  "Время доставки": "Delivery time",
  "Стоимость доставки": "Delivery fee",
  "При заказе до": "For orders below",
  "При заказе от": "For orders from",
  "Понятно": "Got it",
  "Определяем адрес…": "Finding your address…",
  "Редактировать профиль": "Edit profile",
  "Готов принимать заказы": "Ready to accept orders",
  "Включите, чтобы принимать заказы": "Go online to accept orders",
  "Личные данные": "Personal details",
  "Выполнено заказов": "Completed orders",
  "Озвучивать маршрут": "Voice guidance",
  "Какие заказы принимать": "Orders to accept",
  "Поездки Комфорт": "Comfort rides",
  "Недоступен вам": "Unavailable for your vehicle",
  "Тема оформления": "Appearance",
  "Условия использования ↗": "Terms of Use ↗",
  "Как в системе": "Use device setting",
  "Светлая": "Light",
  "Тёмная": "Dark",
  "Эконом": "Economy",
  "Обычные поездки": "Standard rides",
  "Комфорт": "Comfort",
  "Доставка на машине": "Delivery by car",
  "Небольшие чистые грузы": "Small clean parcels",
  "Грузовая доставка": "Freight delivery",
  "Крупные грузы": "Large loads",
  "Синий автомобиль": "Blue car",
  "Спасибо\nза ваш отзыв!": "Thank you\nfor your feedback!",
  "Ваше мнение помогает нам\nделать Atlas лучше": "Your feedback helps us\nmake Atlas better",
  "Отлично": "Great",
  "Заказ успешно\nвыполнен!": "Order\ncompleted!",
  "Стандарт": "Standard",
  "Оставьте комментарий (необязательно)": "Leave a comment (optional)",
  "Комментарий к доставке": "Delivery feedback",
  "Комментарий к поездке": "Trip feedback",
  "Отправить": "Send",
  "Назад к заказу": "Back to order",
  "Пропустить оценку": "Skip rating",
  "Общий путь": "Total distance",
  "Время в пути": "Travel time",
  "Как всё прошло?": "How did it go?",
  "Оцените заказчика": "Rate the customer",
  "Не удалось сохранить отзыв. Попробуйте ещё раз.": "Could not save your review. Try again.",
  "Разрешите доступ к камере, чтобы сделать фото.": "Allow camera access to take a photo.",
  "Поездка": "Trip",
  "Открыть фотографию": "Open photo",
  "Фото готово к отправке": "Photo ready to send",
  "Убрать фото": "Remove photo",
  "Прикрепить фото": "Attach photo",
  "Сообщение": "Message",
  "Сообщение...": "Message...",
  "Закрыть выбор фото": "Close photo picker",
  "Добавить фото": "Add photo",
  "Сделать фото": "Take photo",
  "Открыть камеру": "Open camera",
  "Выбрать из галереи": "Choose from gallery",
  "Фото с устройства": "Photo from device",
  "Поездка по вашему маршруту": "Trip along your route",
  "Написать": "Message",
  "Детали": "Details",
  "Вернуться к доставке": "Back to delivery",
  "Вернуться к поездке": "Back to trip",
  "Оценить пассажира": "Rate the passenger",
  "Назначенный класс: Комфорт": "Assigned class: Comfort",
  "Назначенный класс: Грузовой": "Assigned class: Freight",
  "Назначенный класс: Эконом": "Assigned class: Economy",
  "Не удалось открыть карту. Повторите попытку.": "Could not open the map. Try again.",
  "Повторить загрузку": "Retry loading",
  "Маршрут временно недоступен": "Route temporarily unavailable",
  "Пешком": "On foot",
  "Велосипед": "Bicycle",
  "Электровелосипед": "Electric bike",
  "Мопед": "Moped",
  "Скутер": "Scooter",
  "Мотоцикл": "Motorcycle",
  "Легковой автомобиль": "Passenger car",
  "Грузовой автомобиль": "Truck",
  "Документы": "Documents",
  "Посылки": "Parcels",
  "Продукты": "Products",
  "Готовая еда": "Ready food",
  "Лекарства": "Medicines",
  "Крупные заказы": "Large orders",
  "Задняя": "Rear",
  "Боковая": "Lateral",
  "Верхняя": "Upper",
  "Спереди": "Front",
  "Сзади": "From behind",
  "Левая сторона": "Left side",
  "Правая сторона": "Right side",
  "Передняя часть салона": "Front part of the cabin",
  "Задний ряд": "Back row",
  "Багажник": "trunk",
  "Кабина": "Cabin",
  "Грузовой отсек": "Cargo compartment",
  "Государственный номер": "State number",
  "Основной автомобиль такси": "Main taxi car",
  "номер не указан": "number not specified",
  "Дополнительный автомобиль такси": "Additional taxi car",
  "Основной грузовой транспорт": "Main freight transport",
  "Дополнительный грузовой транспорт": "Additional cargo transport",
  "Как хотите работать?": "How do you want to work?",
  "Можно выбрать несколько направлений — общие сведения заполняются только один раз.": "You can select several directions - general information is filled out only once.",
  "Можно совмещать": "Can be combined",
  "Выберите одно или несколько направлений. Следующие шаги автоматически подстроятся под ваш выбор.": "Select one or more directions. The following steps will automatically adjust to your selection.",
  "Укажите данные как в удостоверении личности. Они используются для всех направлений.": "Enter the details as on your ID. They are used for all directions.",
  "Фамилия": "Last name",
  "Дата рождения": "Date of birth",
  "Город работы": "City of work",
  "Выберите город": "Select a city",
  "Фото увидят клиенты после назначения заказа.": "Customers will see the photo after placing an order.",
  "Лицо хорошо видно и находится в центре": "The face is clearly visible and in the center",
  "На фото только один человек": "There is only one person in the photo",
  "Хорошее освещение без бликов": "Good lighting without glare",
  "Без тёмных очков и закрытого лица": "Without dark glasses and a covered face",
  "ID-карта": "ID card",
  "Загрузите обе стороны ID-карты. Все края документа и текст должны быть хорошо видны.": "Upload both sides of the ID card. All edges of the document and text should be clearly visible.",
  "Действителен до": "Valid until",
  "ДД.ММ.ГГГГ": "DD.MM.YYYY",
  "Как будете доставлять?": "How will you deliver?",
  "Можно выбрать несколько способов доставки.": "You can choose several delivery methods.",
  "Использовать добавленный транспорт": "Use added transport",
  "Можно выбрать конкретную основную или дополнительную машину. Пустой выбор создаст отдельный транспорт курьера.": "You can select a specific primary or secondary machine. An empty selection will create a separate courier transport.",
  "Для доставки пешком, на велосипеде, электровелосипеде или скутере из документов нужна только ID-карта. Для остальных способов доставки потребуются права и документы транспорта.": "For delivery on foot, by bicycle, electric bike or scooter, all you need is an ID card. For other delivery methods, licenses and transport documents will be required.",
  "Водительское удостоверение": "Driver's license",
  "Загрузите обе стороны удостоверения и укажите категории и срок действия.": "Upload both sides of the ID and specify the categories and expiration date.",
  "Категории *": "Categories *",
  "Основной автомобиль": "Main car",
  "Укажите основные данные автомобиля.": "Provide basic vehicle details.",
  "Укажите основные данные грузового транспорта.": "Indicate the basic data of freight transport.",
  "Основной транспорт курьера": "Main courier transport",
  "Моторный транспорт требует отдельной карточки и документов.": "Motor transport requires a separate card and documents.",
  "Документы основного автомобиля": "Documents of the main car",
  "Документы основного грузового транспорта": "Documents of the main freight transport",
  "Фотографии основного автомобиля": "Photos of the main car",
  "Фотографии основного транспорта": "Photos of main transport",
  "Оснащение основного транспорта": "Basic transport equipment",
  "Укажите возможности основной машины — они влияют на доступные заказы.": "Specify the capabilities of the main machine - they affect the available orders.",
  "Расскажите, какие заказы вам подходят.": "Tell us which orders suit you.",
  "Есть термосумка": "There is a thermal bag",
  "Типы заказов *": "Order types *",
  "Максимальный вес": "Maximum weight",
  "кг": "kg",
  "Принимать наличные": "Accept cash",
  "Районы · необязательно": "Districts · optional",
  "Санитарная книжка": "Sanitary book",
  "лицевая сторона": "front side",
  "обратная сторона": "reverse side",
  "Обязательный документ": "Mandatory document",
  "Необязательно": "Optional",
  "График и территория": "Schedule and territory",
  "Необязательный раздел. Настройки можно изменить позже.": "Optional section. Settings can be changed later.",
  "Город": "City",
  "Районы": "Districts",
  "График": "Schedule",
  "Полный": "Full",
  "Свободный": "Free",
  "Предпочтительное время": "Preferred time",
  "Например, 09:00–18:00": "For example, 09:00–18:00",
  "Расстояние до подачи": "Feed distance",
  "км": "km",
  "Междугородние заказы": "Intercity orders",
  "Ночные заказы": "Night orders",
  "Уведомления о новых заказах": "New order notifications",
  "Геолокация": "Geolocation",
  "Она нужна, чтобы находить заказы рядом. Точное местоположение можно не предоставлять сейчас.": "It is needed to find orders nearby. The exact location may not be provided at this time.",
  "Заказы рядом с вами": "Orders near you",
  "Разрешение запрашивается только после вашего действия. Фоновый доступ понадобится отдельно при выходе на линию.": "Permission is requested only after your action. Background access will be required separately when accessing the line.",
  "Разрешить геолокацию": "Allow geolocation",
  "Выбрать город вручную": "Select city manually",
  "Платёжные данные": "Payment details",
  "Можно пропустить и добавить способ выплат позже.": "You can skip and add a payment method later.",
  "Способ выплаты": "Payment method",
  "Банковская карта": "Bank card",
  "Банковский счёт": "Bank account",
  "Электронный кошелёк": "Electronic wallet",
  "Последние 4 цифры": "Last 4 digits",
  "Сохранено безопасно": "Stored Safely",
  "Введите только последние четыре цифры. Полные реквизиты должны передаваться платёжному провайдеру по защищённому каналу.": "Enter only the last four digits. Full details must be transmitted to the payment provider via a secure channel.",
  "Проверьте анкету": "Check your profile",
  "Проверьте исправления": "Check the fixes",
  "Перед отправкой убедитесь, что данные заполнены верно.": "Before sending, make sure that the information is filled out correctly.",
  "Показаны только разделы и документы, которые были возвращены на исправление.": "Only sections and documents that have been returned for correction are shown.",
  "Необязательно · пропущено": "Optional · omitted",
  "Заполнено": "Completed",
  "Требует внимания": "Needs attention",
  "· необязательно": "· optional",
  "Исправление замечаний": "Correction of comments",
  "Поля и файлы, которые не были возвращены на исправление, доступны только для просмотра.": "Fields and files that were not returned for correction are viewable only.",
  "Пример фотографии": "Sample photo",
  "Перед загрузкой сверьтесь с примером, указанным в требованиях документа.": "Please refer to the example provided in the document requirements before downloading.",
  "Обязательный файл": "Required file",
  "Срок действия скоро закончится": "Expires soon",
  "Срок действия закончился": "Expired",
  "Срок действия документа": "Document validity period",
  "Требования к фотографии": "Photo requirements",
  "Владение *": "Possession *",
  "Собственный": "Own",
  "Арендованный": "Rented",
  "Тип транспорта": "Type of transport",
  "Выберите тип": "Select type",
  "Марка": "Brand",
  "Модель": "Model",
  "Год": "Year",
  "Цвет": "Color",
  "Грузоподъёмность": "Load capacity",
  "Дополнительные машины": "Additional machines",
  "Дополнительная машина": "Additional machine",
  "Новая машина": "New car",
  "Тип загрузки *": "Load type *",
  "Количество паллет": "Number of pallets",
  "Рефрижератор": "Refrigerator",
  "Мин. температура": "Min. temperature",
  "Макс. температура": "Max. temperature",
  "Гидроборт": "Tail lift",
  "Манипулятор": "Manipulator",
  "Работа с грузчиками": "Working with movers",
  "Количество грузчиков": "Number of movers",
  "Список требований приходит с сервера и может меняться в зависимости от страны и выбранного транспорта.": "The list of requirements comes from the server and may vary depending on the country and the selected transport.",
  "Сделайте одно фото спереди под углом. Автомобиль должен полностью помещаться в кадре, а госномер — хорошо читаться.": "Take one photo from the front at an angle. The car must fit completely within the frame, and the license plate must be clearly readable.",
  "Обязательный ракурс": "Mandatory angle",
  "Помощь": "Help",
  "Шаг": "Step",
  "· только чтение": "read only",
  "не выбрана": "not selected",
  "Выберите дату": "Select date",
  "Отмена": "Cancel",
  "Не загружено": "Not loaded",
  "Черновик": "Draft",
  "Загрузка": "Loading",
  "Загружено": "Uploaded",
  "Проверяется": "Checked",
  "Одобрено": "Approved",
  "Действует": "Valid",
  "Заблокировано": "Blocked",
  "Исправьте": "Correct",
  "Отклонено": "Rejected",
  "Истекает": "Expires",
  "Просрочено": "Overdue",
  "В очереди": "In line",
  "Фото увидят клиенты после назначения заказа": "Customers will see the photo after placing an order.",
  "Заменить фото": "Replace photo",
  "Нажмите, чтобы загрузить": "Click to download",
  "Обязательно": "Required",
  "Не удалось сохранить": "Failed to save",
  "Нет подключения": "No connection",
  "Последний черновик сохранён. Изменения отправятся после восстановления сети.": "The latest draft has been saved. The changes will be sent after the network is restored.",
  "Проверьте подключение к интернету и повторите попытку.": "Check your internet connection and try again.",
  "Водитель такси": "Taxi driver",
  "Перевозите пассажиров на легковом автомобиле.": "Transport passengers in a passenger car.",
  "Грузовой водитель": "Freight driver",
  "Выполняйте грузовые перевозки на своём или арендованном транспорте.": "Carry out cargo transportation using your own or rented transport.",
  "Курьер": "Courier",
  "Доставляйте посылки, документы, продукты и другие заказы.": "Deliver parcels, documents, groceries and other orders.",
  "Кыргызстан": "Kyrgyzstan",
  "Казахстан": "Kazakhstan",
  "Россия": "Russia",
  "Узбекистан": "Uzbekistan",
  "Таджикистан": "Tajikistan",
  "Бишкек": "Bishkek",
  "Ош": "Osh",
  "Джалал-Абад": "Jalal-Abad",
  "Каракол": "Karakol",
  "Токмок": "Tokmok",
  "Нарын": "Naryn",
  "Талас": "Talas",
  "Баткен": "Batken",
  "Ленинский": "Leninsky",
  "Октябрьский": "Oktyabrsky",
  "Первомайский": "Pervomaisky",
  "Свердловский": "Sverdlovsky",
  "Центр": "Center",
  "Ак-Тилек": "Ak-Tilek",
  "Черёмушки": "Cheryomushki",
  "Пикап": "Pickup",
  "Минивэн": "Minivan",
  "Каблук": "heel",
  "Фургон": "Van",
  "Бортовой": "Onboard",
  "Тентованный": "Tent",
  "Эвакуатор": "Tow truck",
  "Самосвал": "Dump truck",
  "Тягач": "Tractor",
  "Другое": "Other",
  "Седан": "Sedan",
  "Хэтчбек": "Hatchback",
  "Универсал": "Station wagon",
  "Кроссовер": "Crossover",
  "Бизнес": "Business",
  "Кыргызча": "Kyrgyzcha",
  "Удостоверение личности": "Identity card",
  "Также требуется для моторизованной доставки": "Also required for motorized delivery",
  "Документы автомобиля": "Car documents",
  "Фотографии автомобиля такси": "Taxi car photos",
  "Документы грузового автомобиля": "Truck documents",
  "Фотографии грузового автомобиля": "Truck photos",
  "Документы транспорта курьера": "Courier transport documents",
  "Только для моторизованной доставки с отдельным транспортом": "Only for motorized delivery with separate transport",
  "Фотография транспорта курьера": "Photo of courier transport",
  "Договор аренды или доверенность": "Lease agreement or power of attorney",
  "Только для арендованного транспорта": "Only for rented vehicles",
  "Подтверждаю достоверность указанных данных": "I confirm the accuracy of the information provided",
  "Принимаю условия работы исполнителя": "I accept the terms and conditions of the performer",
  "Удостоверение личности · лицевая сторона": "Identity card front side",
  "Удостоверение личности · обратная сторона": "Identity card reverse side",
  "Водительское удостоверение · лицевая сторона": "Driver's license front side",
  "Водительское удостоверение · обратная сторона": "Driver's license reverse side",
  "Такси · свидетельство о регистрации": "Taxi · registration certificate",
  "Такси · страховой полис": "Taxi · insurance policy",
  "Такси · технический осмотр": "Taxi · technical inspection",
  "Такси · договор аренды или доверенность": "Taxi · rental agreement or power of attorney",
  "Грузовой транспорт · свидетельство о регистрации": "Freight transport · registration certificate",
  "Грузовой транспорт · страховой полис": "Freight transport · insurance policy",
  "Грузовой транспорт · технический осмотр": "Freight transport · technical inspection",
  "Грузовой транспорт · договор аренды или доверенность": "Freight transport · lease agreement or power of attorney",
  "Транспорт курьера · свидетельство о регистрации": "Courier transport · registration certificate",
  "Транспорт курьера · страховой полис": "Courier transport · insurance policy",
  "спереди": "front",
  "сзади": "behind",
  "левая сторона": "left side",
  "правая сторона": "right side",
  "передняя часть салона": "front part of the cabin",
  "задний ряд": "back row",
  "багажник": "trunk",
  "кабина": "cabin",
  "грузовой отсек": "cargo compartment",
  "государственный номер": "state number",
  "Грузовой транспорт": "Freight transport",
  "Транспорт курьера": "Courier transport",
  "фотография транспорта": "transport photography",
  "Дополнительный документ": "Additional document",
  "Истёк": "Expired",
  "Действует до": "Valid until",
  "Локальный файл недоступен. Выберите его ещё раз.": "The local file is not available. Select it again.",
  "Не удалось сохранить файл для офлайн-загрузки. Выберите его ещё раз.": "Failed to save file for offline download. Select it again.",
  "Для отправки анкеты нужно подключение к интернету.": "An Internet connection is required to submit the form.",
  "Дождитесь загрузки всех файлов или повторите неудачную загрузку.": "Please wait until all files are downloaded or try the failed download again.",
  "Сохранение занимает больше времени, чем обычно. Повторите попытку.": "Saving takes longer than usual. Please try again.",
  "Во время исправления можно заменить только отмеченный проверкой файл.": "During repair, you can replace only the file marked by the check.",
  "Разрешите доступ к фотографиям или выберите файл.": "Allow access to photos or select a file.",
  "Этот формат файла не поддерживается.": "This file format is not supported.",
  "Во время исправления можно удалить только отмеченный проверкой файл.": "During repair, you can only delete the file that has been checked.",
  "Заполните обязательный раздел перед отправкой.": "Complete the required section before submitting.",
  "Подтвердите обновлённые условия": "Confirm the updated terms",
  "Примите обновлённые условия": "Accept the updated terms",
  "черновик": "draft",
  "не выбраны": "not selected",
  "Допуск уже одобрен. Обновите приложение через несколько секунд.": "The permit has already been approved. Please update the app after a few seconds.",
  "Отправить исправления": "Submit corrections",
  "Сохранить исправление": "Save the fix",
  "Отправить на проверку": "Submit for review",
  "Добавить файл": "Add file",
  "Сфотографировать": "Take a photo",
  "Откроется камера": "The camera will open",
  "JPEG, PNG или WEBP": "JPEG, PNG or WEBP",
  "Выбрать файл": "Select file",
  "Изображение или PDF, до 12 МБ": "Image or PDF, up to 12 MB",
  "Есть несохранённые изменения": "There are unsaved changes",
  "Черновик сохранён на этом устройстве. При наличии интернета мы также отправим его на сервер.": "The draft is saved on this device. If there is internet, we will also send it to the server.",
  "Сохранить и закрыть": "Save and close",
  "Сохранить и выйти": "Save and exit",
  "Продолжить заполнение": "Continue filling",
  "Закрыть без сохранения": "Close without saving",
  "Выйти без сохранения": "Exit without saving",
  "Сохраняем изменения": "Save changes",
  "Черновик сохранён": "Draft saved",
  "Сохранено на устройстве": "Saved on device",
  "Не удалось сохранить локально": "Failed to save locally",
  "Не удалось загрузить данные": "Failed to load data",
  "Проверьте подключение к интернету и попробуйте ещё раз. Ваши заполненные данные останутся на устройстве.": "Check your internet connection and try again. Your completed data will remain on the device.",
  "Попробовать снова": "Try again",
  "Фото профиля": "Profile photo",
  "Чтобы клиенты узнавали вас": "So that clients recognize you",
  "Для быстрой и безопасной проверки": "For fast and safe verification",
  "Транспорт": "Transport",
  "Чтобы подтвердить данные автомобиля": "To confirm vehicle details",
  "Безопасность": "Security",
  "Фото защищены и доступны только проверке": "Photos are protected and only available for verification",
  "Разрешите доступ к камере": "Allow access to the camera",
  "Камера нужна, чтобы быстро сделать фотографию профиля, документов и транспорта.": "A camera is needed to quickly take a photo of your profile, documents and vehicles.",
  "Все данные защищены и используются только для проверки": "All data is protected and is used only for verification",
  "Расположите лицо в центре": "Place your face in the center",
  "Поместите объект полностью в рамку": "Place the object entirely within the frame",
  "Все края видны · без бликов · держите камеру ровно": "All edges visible · no glare · keep camera level",
  "Камера недоступна": "Camera not available",
  "Запрашиваем доступ к камере": "Requesting access to the camera",
  "Разрешите доступ в настройках устройства или выберите фото из галереи.": "Allow access in your device settings or select a photo from the gallery.",
  "Подтвердите системный запрос, чтобы продолжить.": "Confirm the system prompt to continue.",
  "Предварительный просмотр": "Preview",
  "Проверьте качество": "Check the quality",
  "Все края видны · нет бликов · текст читается": "All edges visible · no glare · text readable",
  "Использовать файл": "Use file",
  "Снять или выбрать заново": "Remove or select again",
  "Контекст уже добавлен": "Context has already been added",
  "С чем помочь?": "Help with what?",
  "Не приходит сообщение": "Message doesn't arrive",
  "Статус анкеты": "Profile status",
  "Другая проблема": "Another problem",
  "Опишите, что произошло": "Describe what happened",
  "Прикрепить изображение или файл": "Attach an image or file",
  "После открытия приложения сообщений добавьте выбранный файл к обращению.": "After opening the Messages app, add the selected file to the case.",
  "Написать в поддержку": "Write to support",
  "Документы и фотографии": "Documents and photographs",
  "Документ требует внимания": "Document requires attention",
  "Загрузить новый документ": "Upload a new document",
  "Загрузить заново": "Upload again",
  "Вы готовы к работе!": "You're ready to go!",
  "Нужны исправления": "Need corrections",
  "Регистрация отклонена": "Registration rejected",
  "Доступ ограничен": "Access limited",
  "Анкета отправлена": "Questionnaire sent",
  "Анкета на проверке": "Questionnaire for verification",
  "Направления с допуском уже готовы к работе.": "Directions with clearance are already ready to work.",
  "Исправьте только отмеченные пункты — проходить регистрацию заново не нужно.": "Correct only the marked items - you do not need to register again.",
  "Причину и возможные дальнейшие действия можно уточнить в поддержке.": "The reason and possible further actions can be clarified in support.",
  "Некоторые возможности аккаунта временно ограничены.": "Some account features are temporarily limited.",
  "Мы получили анкету. Статусы обновляются с сервера автоматически.": "We received the questionnaire. Statuses are updated automatically from the server.",
  "создана": "created",
  "Срок проверки обновляется сервером и появится здесь.": "The verification period is updated by the server and will appear here.",
  "Временное ограничение": "Time limit",
  "Допуск зависит от другого направления, которое ещё не одобрено.": "Admission depends on another direction that has not yet been approved.",
  "Не хватает данных транспорта для подключения направления.": "There is not enough transport data to connect the direction.",
  "Направление одобрено, но профиль требует проверки поддержки.": "The referral has been approved, but the profile requires verification of support.",
  "Эти возможности пока нельзя одновременно подключить к профилю.": "These features cannot yet be connected to a profile at the same time.",
  "Направление одобрено, но текущая версия поддерживает один активный транспорт.": "The direction is approved, but the current version supports one active transport.",
  "Направление одобрено, но пока не подключено к рабочему профилю.": "The direction has been approved, but is not yet connected to the work profile.",
  "Грузовые перевозки": "Freight transport",
  "Откройте отмеченный сервером раздел и исправьте только указанные данные.": "Open the section marked by the server and correct only the specified data.",
  "Перейти к исправлениям": "Go to corrections",
  "Исправить анкету": "Correct the profile",
  "Начать работу": "Get started",
  "Обновить статус": "Update status",
  "Начать работу по одобренному направлению": "Start working in the approved direction",
  "Связаться с поддержкой": "Contact support",
};
