import React, { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { api, messageOf, requestId } from './api';
import { searchAddresses } from './native/search';
import { ChatMessage, Point, User } from './types';
import { Button, colors, Empty, Icon, IconButton, s, tr } from './ui';

export function AddressPicker({ field, center, language, onSelect, onClose, onMap, onLocation }: { field: 'pickup' | 'dropoff'; center?: Point | null; language: User['language']; onSelect: (point: Point) => void; onClose: () => void; onMap: () => void; onLocation: () => void }) {
  const t = tr(language); const [query, setQuery] = useState(''); const [results, setResults] = useState<Point[]>([]); const [loading, setLoading] = useState(false); const [error, setError] = useState('');
  useEffect(() => {
    if (query.trim().length < 3) { setResults([]); setLoading(false); return; }
    let live = true;
    const timer = setTimeout(async () => { setLoading(true); setError(''); try {
      const points = Platform.OS === 'web' || !process.env.EXPO_PUBLIC_YANDEX_MAPKIT_KEY ? await api.request<Point[]>(`/places/search?q=${encodeURIComponent(query.trim())}`) : await searchAddresses(query, center || undefined);
      if (live) setResults(points);
    } catch (e) { if (live) setError(messageOf(e)); } finally { if (live) setLoading(false); } }, 450);
    return () => { live = false; clearTimeout(timer); };
  }, [query, center?.latitude, center?.longitude]);
  return <Modal animationType="slide" onRequestClose={onClose}><SafeAreaView style={{ flex: 1, backgroundColor: 'white' }}><View style={[s.spread, { padding: 20 }]}><IconButton name="arrow-back" label={t('Назад')} onPress={onClose}/><Text style={s.h2}>{t(field === 'pickup' ? 'Откуда' : 'Куда')}</Text><View style={{ width: 44 }}/></View><View style={{ paddingHorizontal: 20, gap: 14 }}><View style={[s.input, s.row]}><Icon name="search" color={colors.blue}/><TextInput autoFocus style={{ flex: 1, fontSize: 17, color: colors.ink }} accessibilityLabel={t('Найти адрес')} placeholder={t('Найти адрес')} value={query} onChangeText={setQuery}/>{loading && <ActivityIndicator color={colors.blue}/>}</View><View style={s.row}><View style={{ flex: 1 }}><Button secondary label={t('Выбрать на карте')} onPress={onMap} icon="map-outline"/></View></View>{field === 'pickup' && <Pressable style={[s.row, { paddingVertical: 12 }]} onPress={onLocation}><Icon name="navigate" color={colors.blue}/><Text style={{ color: colors.blue, fontWeight: '600' }}>{t('Моё местоположение')}</Text></Pressable>}{error && <Text style={{ color: colors.danger }}>{t(error)}</Text>}{__DEV__ && !process.env.EXPO_PUBLIC_YANDEX_MAPKIT_KEY && <Text style={s.caption}>{t("Development: адреса из тестового каталога сервера. Для поиска любых адресов требуется ключ Яндекс.")}</Text>}</View><ScrollView contentContainerStyle={{ padding: 20 }} keyboardShouldPersistTaps="handled">{results.map((point, index) => <Pressable key={`${point.latitude}:${point.longitude}:${index}`} onPress={() => onSelect(point)} style={[s.row, { paddingVertical: 20, borderBottomWidth: 1, borderBottomColor: colors.line }]}><View style={{ backgroundColor: colors.pale, padding: 12, borderRadius: 14 }}><Icon name="location-outline" color={colors.blue}/></View><Text style={[s.body, { flex: 1 }]}>{point.address}</Text><Icon name="chevron-forward" color={colors.muted} size={17}/></Pressable>)}{query.length >= 3 && !loading && !error && results.length === 0 && <Empty icon="search-outline" title={t("Адрес не найден")} subtitle={t("Уточните название улицы или выберите точку на карте.")}/>}</ScrollView></SafeAreaView></Modal>;
}

export function ChatOverlay({ orderId, user, incoming, onClose, onError }: { orderId: string; user: User; incoming: ChatMessage | null; onClose: () => void; onError: (message: string) => void }) {
  const t = tr(user.language); const [messages, setMessages] = useState<ChatMessage[]>([]); const [text, setText] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const key = useRef<{ text: string; id: string } | null>(null); const scroll = useRef<ScrollView>(null);
  const add = (message: ChatMessage) => setMessages(current => current.some(item => item.id === message.id) ? current : [...current, message].sort((a, b) => a.createdAt.localeCompare(b.createdAt)));
  async function refresh() { try { const list = await api.request<ChatMessage[]>(`/orders/${orderId}/messages`); setMessages(current => { const combined = new Map([...current, ...list].map(item => [item.id, item])); return [...combined.values()].sort((a, b) => a.createdAt.localeCompare(b.createdAt)); }); } catch (e) { onError(messageOf(e)); } finally { setLoading(false); } }
  useEffect(() => { void refresh(); const timer = setInterval(refresh, 10000); return () => clearInterval(timer); }, [orderId]);
  useEffect(() => { if (incoming?.orderId === orderId) add(incoming); }, [incoming?.id]);
  async function send() { const body = text.trim(); if (!body) return; if (key.current?.text !== body) key.current = { text: body, id: requestId() }; setSending(true); try { const message = await api.post<ChatMessage>(`/orders/${orderId}/messages`, { text: body, clientMessageId: key.current.id }); add(message); setText(''); key.current = null; } catch (e) { onError(messageOf(e)); } finally { setSending(false); } }
  return <Modal animationType="slide" onRequestClose={onClose}><SafeAreaView style={{ flex: 1, backgroundColor: '#F4F8FD' }}><KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><View style={[s.spread, { padding: 18, backgroundColor: 'white' }]}><IconButton name="arrow-back" label={t('Назад')} onPress={onClose}/><Text style={s.h2}>{t('Чат')}</Text><View style={{ width: 44 }}/></View><ScrollView ref={scroll} contentContainerStyle={{ padding: 20, gap: 12, flexGrow: 1 }} onContentSizeChange={() => scroll.current?.scrollToEnd({ animated: true })}>{loading && <ActivityIndicator color={colors.blue}/>}{!loading && messages.length === 0 && <Empty icon="chatbubbles-outline" title={t('Напишите первое сообщение')}/>}{messages.map(message => { const mine = message.senderId === user.id; return <View key={message.id} style={{ backgroundColor: mine ? colors.blue : 'white', alignSelf: mine ? 'flex-end' : 'flex-start', maxWidth: '84%', padding: 13, borderRadius: 18, borderBottomRightRadius: mine ? 5 : 18, borderBottomLeftRadius: mine ? 18 : 5 }}><Text style={{ color: mine ? 'white' : colors.ink, fontSize: 16, lineHeight: 23 }}>{message.text}</Text><Text style={{ color: mine ? '#C9E5FF' : colors.muted, fontSize: 10, marginTop: 6, textAlign: 'right' }}>{new Date(message.createdAt).toLocaleTimeString(user.language === 'ky' ? 'ky-KG' : 'ru-RU', { hour: '2-digit', minute: '2-digit' })}</Text></View>; })}</ScrollView><View style={[s.row, { padding: 16, backgroundColor: 'white' }]}><TextInput accessibilityLabel={t('Ваше сообщение')} value={text} onChangeText={setText} multiline maxLength={1000} placeholder={t('Ваше сообщение')} style={[s.input, { flex: 1, maxHeight: 100 }]}/><Pressable accessibilityRole="button" accessibilityLabel={t("Отправить сообщение")} disabled={sending || !text.trim()} onPress={send} style={{ backgroundColor: colors.blue, borderRadius: 18, width: 52, height: 52, alignItems: 'center', justifyContent: 'center', opacity: sending || !text.trim() ? .5 : 1 }}>{sending ? <ActivityIndicator color="white"/> : <Icon name="send" color="white"/>}</Pressable></View></KeyboardAvoidingView></SafeAreaView></Modal>;
}
