import 'reflect-metadata';
import assert from 'node:assert/strict';
import {test} from 'node:test';
import {BadRequestException,ConflictException,ForbiddenException} from '@nestjs/common';
import {ProfileSelfService} from '../src/profile-self-service';
import {FoodService} from '../src/food';
import {UsersController} from '../src/http';
const actor:any={id:'driver-id',role:'DRIVER'};
function fixture() {
  const vehicle:any={ownership:'OWN',brand:'Toyota',model:'Camry',year:'2020',color:'Белый',plateNumber:'01 123 AAA'};
  const state:any={user:{name:'Иванов Иван',deletedAt:null,driverProfile:{transportClass:'ECONOMY',vehicle:{make:'Toyota Camry',color:'Белый',plate:'01 123 AAA'}}},application:{id:'application-id',version:5,data:{personal:{firstName:'Иван',lastName:'Иванов',birthDate:'01.01.1990',city:'Шамалды-Сай'},taxiVehicle:vehicle,vehicles:[]},roles:[{selected:true,role:'TAXI_DRIVER'}],uploads:[]},active:false,activeFood:false,duplicate:false,revoked:false,pushRemoved:false,photoRemoved:false};
  const events:any[]=[];
  const tx:any={$queryRaw:async()=>[],user:{findUniqueOrThrow:async()=>({...state.user,performerApplication:state.application}),update:async({data}:any)=>Object.assign(state.user,data),updateMany:async({data}:any)=>{Object.assign(state.user,data);return {count:1};}},performerApplication:{update:async({data}:any)=>{state.application.data=data.data;state.application.version++;},deleteMany:async()=>{state.application=null;}},performerUpload:{deleteMany:async()=>{state.photoRemoved=true;}},order:{findFirst:async()=>state.active?{id:'active'}:null},foodOrder:{findFirst:async()=>state.activeFood?{id:'food'}:null},vehicle:{findFirst:async()=>state.duplicate?{id:'other'}:null,upsert:async({update}:any)=>Object.assign(state.user.driverProfile.vehicle,update),updateMany:async({data}:any)=>Object.assign(state.user.driverProfile.vehicle,data)},driverProfile:{updateMany:async({data}:any)=>Object.assign(state.user.driverProfile,data)},refreshSession:{updateMany:async()=>{state.revoked=true;}},pushToken:{deleteMany:async()=>{state.pushRemoved=true;}}};
  const db:any={...tx,$transaction:async(work:any)=>{const backup=structuredClone(state);try{return await work(tx);}catch(e){Object.assign(state,backup);throw e;}}};
  const auth:any={user:async()=>state.user};
  const service=new ProfileSelfService(db,auth,{registrationConfig:async()=>({cities:['Шамалды-Сай'],acceptedCityNames:['Шамалды-Сай'],comingSoonCities:['Кочкор-Ата','Кербен']})} as any,{publish:(...args:any[])=>events.push(args),adminChanged(){}} as any);
  return {state,tx,db,auth,service,events};
}
test('driver sees his registration values, edits names and preserves registration status and version',async()=>{const h=fixture();assert.equal((await h.service.details(actor)).personal.birthDate,'01.01.1990');await h.service.save(actor,{version:5,personal:{firstName:'Пётр',lastName:'Иванов'}});assert.equal(h.state.user.name,'Иванов Пётр');assert.equal(h.state.application.version,6);assert.equal(h.state.application.data.personal.city,'Шамалды-Сай');assert.equal(h.events[0][1],'profile:updated');await assert.rejects(h.service.details({...actor,role:'CLIENT'}),ForbiddenException);});
test('optimistic conflict, unavailable city and unsupported personal fields cannot modify a profile',async()=>{for(const dto of [{version:4,personal:{firstName:'X'}},{version:5,personal:{city:'Кербен'}},{version:5,personal:{role:'ADMIN'}}]){const h=fixture();await assert.rejects(h.service.save(actor,dto));assert.equal(h.state.application.version,5);assert.equal(h.state.user.name,'Иванов Иван');}});
test('car edits update registration and the actual passenger-visible vehicle',async()=>{const h=fixture();await h.service.save(actor,{version:5,vehicleKey:'taxiVehicle',vehicle:{brand:'Hyundai',model:'Elantra',plateNumber:'02 321 AAA'}});assert.equal(h.state.application.data.taxiVehicle.model,'Elantra');assert.equal(h.state.user.driverProfile.vehicle.make,'Hyundai Elantra');assert.equal(h.state.user.driverProfile.vehicle.plate,'02 321 AAA');});
test('foreign vehicle keys, duplicate plates and active trips reject car changes atomically',async()=>{for(const mode of ['foreign','duplicate','active']){const h=fixture();h.state.duplicate=mode==='duplicate';h.state.active=mode==='active';await assert.rejects(h.service.save(actor,{version:5,vehicleKey:mode==='foreign'?'v-foreign':'taxiVehicle',vehicle:{brand:'Kia'}}));assert.equal(h.state.application.version,5);assert.equal(h.state.user.driverProfile.vehicle.make,'Toyota Camry');}});
test('legacy registered drivers retain access to their existing vehicle with an empty old application',async()=>{const h=fixture();h.state.application.roles=[];h.state.application.data.taxiVehicle={};const details=await h.service.details(actor);assert.equal(details.vehicles.length,1);assert.equal(details.vehicles[0].vehicle.model,'Camry');assert.equal(details.vehicles[0].vehicle.plateNumber,'01 123 AAA');});
test('account removal erases personal profile and uploads, revokes all sessions and clears location',async()=>{const h=fixture();await h.service.removeAccount(actor);assert.ok(h.state.user.deletedAt);assert.equal(h.state.user.phone,'deleted:driver-id');assert.equal(h.state.application,null);assert.equal(h.state.user.driverProfile.verified,false);assert.equal(h.state.user.driverProfile.online,false);assert.equal(h.state.user.driverProfile.locationLatitude,null);assert.equal(h.state.revoked,true);assert.equal(h.state.pushRemoved,true);});
test('account removal is blocked by active food/taxi and unavailable to admin',async()=>{for(const mode of ['taxi','food','admin']){const h=fixture();h.state.active=mode==='taxi';h.state.activeFood=mode==='food';await assert.rejects(h.service.removeAccount(mode==='admin'?{...actor,role:'ADMIN'}:actor));assert.equal(h.state.user.deletedAt,null);assert.equal(h.state.revoked,false);}});
test('removing an avatar also removes the registration copy so projection cannot restore it',async()=>{const h=fixture(),controller=new UsersController(h.db,h.auth,{} as any);await controller.removeAvatar({actor} as any);assert.equal(h.state.user.avatarData,null);assert.equal(h.state.user.avatarMime,null);assert.equal(h.state.photoRemoved,true);await assert.rejects(controller.removeAvatar({actor:{...actor,role:'CLIENT'}} as any),ForbiddenException);});
test('client food cancellation succeeds only before confirmation and is idempotent',async()=>{for(const status of ['PLACED','CONFIRMED','PREPARING','CANCELLED']){let changed=0;const order:any={id:'food',clientId:'client',status};const tx:any={$queryRaw:async()=>[],foodOrder:{findUnique:async()=>order,update:async({data}:any)=>Object.assign(order,data)}};const service=new FoodService({$transaction:async(work:any)=>work(tx)} as any,{} as any,{} as any,{} as any,{publish(){changed++;},adminChanged(){}} as any);if(status==='PLACED'||status==='CANCELLED'){await service.cancel({...actor,id:'client',role:'CLIENT'},'food');assert.equal(order.status,'CANCELLED');assert.equal(changed,status==='PLACED'?1:0);}else{await assert.rejects(service.cancel({...actor,id:'client',role:'CLIENT'},'food'),BadRequestException);assert.equal(order.status,status);}}});
