CREATE TYPE "OrderKind" AS ENUM ('RIDE','DELIVERY_CAR','DELIVERY_TRUCK');
CREATE TYPE "TransportClass" AS ENUM ('ECONOMY','COMFORT','TRUCK');
ALTER TABLE "Tariff" ADD COLUMN "kind" "OrderKind" NOT NULL DEFAULT 'RIDE';
ALTER TABLE "Tariff" ADD COLUMN "requiredClass" "TransportClass" NOT NULL DEFAULT 'ECONOMY';
UPDATE "Tariff" SET "requiredClass"='COMFORT' WHERE "id"='comfort';
ALTER TABLE "Quote" ADD COLUMN "kind" "OrderKind" NOT NULL DEFAULT 'RIDE';
ALTER TABLE "Order" ADD COLUMN "kind" "OrderKind" NOT NULL DEFAULT 'RIDE';
ALTER TABLE "Order" ADD COLUMN "deliveryDetails" JSONB;
ALTER TABLE "Order" ADD COLUMN "dispatchAfter" TIMESTAMP(3) NOT NULL DEFAULT NOW();
ALTER TABLE "DriverProfile" ADD COLUMN "transportClass" "TransportClass" NOT NULL DEFAULT 'ECONOMY';
ALTER TABLE "DriverProfile" ADD COLUMN "requestedTransportClass" "TransportClass";
ALTER TABLE "DriverProfile" ADD COLUMN "acceptsEconomy" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "DriverProfile" ADD COLUMN "acceptsComfort" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "DriverProfile" ADD COLUMN "acceptsDeliveryCar" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "DriverProfile" ADD COLUMN "acceptsDeliveryTruck" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Vehicle" ADD COLUMN "photoData" BYTEA;
ALTER TABLE "Vehicle" ADD COLUMN "photoMime" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN "photoUpdatedAt" TIMESTAMP(3);
CREATE INDEX "Tariff_kind_active_idx" ON "Tariff"("kind", "active");
CREATE INDEX "Order_kind_status_searchExpiresAt_idx" ON "Order"("kind", "status", "searchExpiresAt");
