import { Module } from '@nestjs/common';
import { JwtModule } from '@nestjs/jwt';
import { ScheduleModule } from '@nestjs/schedule';
import { AuthGuard, AuthService, RateLimits } from './auth';
import { AppConfig } from './config';
import { DriverService } from './driver';
import { RealtimeEvents } from './events';
import { TaxiGateway } from './gateway';
import { AdminController, AuthController, DriverController, OrdersController, PublicController, UsersController } from './http';
import { BackgroundJobs } from './jobs';
import { OrdersService } from './orders';
import { PrismaService } from './prisma.service';
import { PushService, RoutingService } from './providers';
import { PlacesController, PlacesService } from './places';
import { RoutesController } from './routes';
import { TrackingController, TrackingService } from './tracking';
import { FoodService } from './food';
import { AdminFoodController, FoodCatalogController, FoodOrdersController } from './food.http';
import { AdminAuditService, AdminGuard } from './admin.security';
import { AdminAuthController, AdminAuthService } from './admin.auth';
import { AdminService } from './admin';
import { AdminOperationsController } from './admin.http';
import { AdminCatalogController, ContentController, ContentService } from './content';
import { RegistrationService } from './registration';
import { RegistrationUploadGate } from './registration-upload-gate';
import { RegistrationController } from './registration.http';
import { RegistrationAdminService } from './registration-admin';
import { RegistrationAdminController } from './registration-admin.http';
@Module({imports:[JwtModule.register({}),ScheduleModule.forRoot()],controllers:[TrackingController,AuthController,UsersController,OrdersController,DriverController,RegistrationController,RegistrationAdminController,AdminController,PublicController,PlacesController,RoutesController,FoodCatalogController,FoodOrdersController,AdminFoodController,AdminAuthController,AdminOperationsController,ContentController,AdminCatalogController],providers:[TrackingService,PrismaService,AppConfig,AuthService,AuthGuard,RateLimits,RoutingService,PushService,RealtimeEvents,OrdersService,DriverService,RegistrationService,RegistrationUploadGate,RegistrationAdminService,TaxiGateway,BackgroundJobs,PlacesService,FoodService,AdminAuditService,AdminGuard,AdminAuthService,AdminService,ContentService]})
export class AppModule {}
